embedding_dim = 768        #initialize dimension of embedding here
MAX_SENT_LENGTH = 150      # Max number of words per sentence
MAX_SENTS = 9             # Max number of sentences per document
trainDataPath = "data/yelp-2013-train.txt.ss" # Initialize train data path here
testDataPath = "data/yelp-2013-test.txt.ss" # Initialize test data path here
valDataPath = "data/yelp-2013-dev.txt.ss" # Initialize validation data path here
epoch = 10                #initialize epoch numebr here
batch_size = 100          #this is the batchsize for HAN model
create_emb = False         # set to True if you want bert created embedding matrix 
save_dir = "EXP1"          #initialize you log saving dir here
lr = 0.001               #initialize learning rate here
resume = None          #initialize your checkpoint path here
is_training = False    #Assign to true if you want to train the network
