embedding_dim = 768
MAX_SENT_LENGTH = 150      # Max number of words per sentence
MAX_SENTS = 12             # Max number of sentences per document
trainDataPath = "../data/yelp-2015-train.txt.ss"
testDataPath = "../data/yelp-2015-test.txt.ss"
valDataPath = "../data/yelp-2015-dev.txt.ss"
epoch = 10
batch_size = 100           #this is the batchsize for HAN model
create_emb = False
save_dir = "EXP1"          #initialize you log saving dir here
lr = 0.001
resume = None              #initialize your checkpoint path here